### ISSUE TITLE
ECONRESET error

### ISSUE THREAD

**Issue by icavalheiro** [BriteVerify/node-sftp-server#23]
Hello, I'm trying to use yout tool to build myself a sftp server.
I just writted a few lines to list on a given port (and i've generated a key file with putty), but once i try to connect with it using filezilla it tryes for a while and then when filezilla tryes to reconnect the server breaks up with ths message: 
`events.js:160
    throw er; // Unhandled 'error' event
    ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)`

Any ideas why this is happening?

**Comment by icavalheiro** [comment]
I've solved that by accepting or rejecting the connection in the callback
