### ISSUE TITLE
When trying to overwrite files - server crashes

### ISSUE THREAD

**Issue by davidAtBar** [BriteVerify/node-sftp-server#33]
Hi,
When i'm trying to overwrite a file the server crashes with the following stacktrace:
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unknown open flags: null
    at SFTPSession.OPEN (*/node_modules/node-sftp-server/node-sftp-server.js:394:35)
    at SFTPStream.<anonymous> (*/node_modules/node-sftp-server/node-sftp-server.js:255:31)
    at emitMany (events.js:127:13)
    at SFTPStream.emit (events.js:201:7)
    at SFTPStream._transform (*/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:572:20)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (*/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)

Process finished with exit code 1`

Does the server support overwrite?

**Comment by davidAtBar** [comment]
It looks like the issue is in the file **node-sftp-server.js** in the method **flagsToString**.
the flags value is 18 and **flagsToString** return null.

`SFTPSession.prototype.OPEN = function(reqid, pathname, flags, attrs) {
    var handle, rs, started, stringflags, ts;
    stringflags = SFTP.flagsToString(flags);`

should be an easy fix no?

**Comment by uberbrady** [comment]
The server should definitely support overwrite, if not, that's definitely a problem.

It feels like there's some kind of bad set of flags being passed, somewhere. Or maybe they're getting misformatted.

If you could paste a snippet of how you're handling the readfile/writefile stuff, that might help us out a little to try and trace down what's wrong.

Or, if you think it's something we're doing, I'd be happy to take a PR or pointers on what exactly it is we're doing wrong so I can fix it.

**Comment by davidAtBar** [comment]
Hey Brady,
Thanks for the reply 👍 
It does not reach the readfile/writefile method it stops in the method **flagsToString** here:

SFTPSession.prototype.OPEN = function(reqid, pathname, flags, attrs) {
    var handle, rs, started, stringflags, ts;
    **stringflags = SFTP.flagsToString(flags);**
    switch (stringflags) {
      case "r":
        // Create a temporary file to hold stream contents.
        var options = {};
        if (SFTPServer.options.temporaryFileDirectory) options.dir = SFTPServer.options.temporaryFileDirectory;
        return tmp.file(options, function (err, tmpPath, fd) {
          if (err) throw err;
          handle = this.fetchhandle();
          this.handles[handle] = {
            mode: "READ",
            path: pathname,
            finished: false,
            tmpPath: tmpPath,
            tmpFile: fd
          };
          var writestream = fs.createWriteStream(tmpPath);
          writestream.on("finish", function () {
            this.handles[handle].finished = true;
          }.bind(this));
          this.emit("readfile", pathname, writestream);
          return this.sftpStream.handle(reqid, handle);
        }.bind(this));
      case "w":
        rs = new Readable();
        started = false;
        rs._read = (function(_this) {
          return function(bytes) {
            if (started) {
              return;
            }
            handle = _this.fetchhandle();
            _this.handles[handle] = {
              mode: "WRITE",
              path: pathname,
              stream: rs
            };
            _this.sftpStream.handle(reqid, handle);
            return started = true;
          };
        })(this);
        return this.emit("writefile", pathname, rs);
      default:
          return this.emit("error", new Error("Unknown open flags: " + stringflags));
    }
  };

**stringflags** in null in the value being passed to SFTP.flagsToString(flags) is **18**.

I looked over at **flagsToString** in sftp.js and perhaps this is where the issue is:

var stringFlagMap = {
  'r': OPEN_MODE.READ,
  'r+': OPEN_MODE.READ | OPEN_MODE.WRITE,
  'w': OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.WRITE,
  'wx': OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.WRITE | OPEN_MODE.EXCL,
  'xw': OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.WRITE | OPEN_MODE.EXCL,
  'w+': OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.READ | OPEN_MODE.WRITE,
  'wx+': OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.READ | OPEN_MODE.WRITE
         | OPEN_MODE.EXCL,
  'xw+': OPEN_MODE.TRUNC | OPEN_MODE.CREAT | OPEN_MODE.READ | OPEN_MODE.WRITE
         | OPEN_MODE.EXCL,
  'a': OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.WRITE,
  'ax': OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.WRITE | OPEN_MODE.EXCL,
  'xa': OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.WRITE | OPEN_MODE.EXCL,
  'a+': OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.READ | OPEN_MODE.WRITE,
  'ax+': OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.READ | OPEN_MODE.WRITE
         | OPEN_MODE.EXCL,
  'xa+': OPEN_MODE.APPEND | OPEN_MODE.CREAT | OPEN_MODE.READ | OPEN_MODE.WRITE
         | OPEN_MODE.EXCL
};

what do you think?
