### ISSUE TITLE
Error: com.jcraft.jsch.JSchException: Auth fail

### ISSUE THREAD

**Issue by ianbale** [BriteVerify/node-sftp-server#39]
I've setup an SFTP server. It appears to work fine from most clients. I can connect, list files, change directories, upload / download files. create / delete directories, delete files etc.

However, one client (A "slightly modified" Jsch) fails to connect every time and results in an unhandled exception (listed below)  that takes the server down.

Any idea why it might be doing this - and how to fix it?

```
Error: com.jcraft.jsch.JSchException: Auth fail
    at onDISCONNECT (/home/frog/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2029:15)
    at SSH2Stream.<anonymous> (/home/frog/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:178:5)
    at emitMany (events.js:146:13)
    at SSH2Stream.emit (events.js:223:7)
    at parsePacket (/home/frog/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3462:10)
    at SSH2Stream._transform (/home/frog/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (/home/frog/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at SSH2Stream.Writable.write (_stream_writable.js:274:11)
    at Socket.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12) code: 3 }
```

With debugging on, I see only these two lines before the crash:

```
SFTP Server: on('authentication')
SFTP Server: error
```

It looks like the key exchange works okay, however as soon as the username is being send as part of the authentication the server sends back command 51 which is SSH_MSG_USERAUTH_FAILURE.
 
Strangely this is even before the password is being sent...

**Comment by ianbale** [comment]
I came across this issue which has already been resolved:

https://github.com/BriteVerify/node-sftp-server/issues/37

It seemed to be related, but I figured it wasn't since it has been fixed and pulled into the project. However, it turns out this is is the fix for my issue.

The problem is that whilst this has been fixed and the code in github updated, npm has not. Can you publish the latest code to npm please? 

At the same time I also added this to my code as a sort of belt and braces approach..:

```
    myserver.on("connect", function(auth) {

        if (auth.method !== 'password') 
        {
            return auth.reject(**['password']**)
        }
```

rather than simply return auth.reject()

**Comment by uberbrady** [comment]
I don't think it has been pulled in, has it? I asked for a pull request and I don't think anyone has managed to do that. I guess I'll have to do it myself.

The only other concern I would have is I still would want people to be able to ssh-key based authentication, and this seems to be forcing everything to be password-only.

I guess I'll have to check it out and fill out the remaining gaps.

Still woulda loved a pull request instead, though.

**Comment by ianbale** [comment]
You're right. I thought I'd seen a pull request with this change. But I was looking at a fork of this repo. 

As you say, this particular fix does not work for those wanting to use ssh key auth. Maybe make the supported auth type configurable in the constructor?

I'm wondering if my code:

        if (auth.method !== 'password') 
        {
            return auth.reject(['password'])
        }

is achieving the same thing without having to modify the base code... I can't test that at the moment though as I don't have a client that causes the problem. I'll need to persuade the company that is sending me the data to spend some more time with me. Hopefully I can get that done this week. Will report back afterwards.

**Comment by uberbrady** [comment]
Check out version 0.3.0 - it has some changes integrated, and might fix your problem.
