### ISSUE TITLE
Overwrite existing file causes error

### ISSUE THREAD

**Issue by ianbale** [BriteVerify/node-sftp-server#40]
If I attempt to overwrite an existing file I get this error thrown:

```
Error: Unknown open flags: null
   at SFTPSession.OPEN (/Users/ianbale/Source Code/noderail-data-feed-manager/node_modules/node-sftp-server/node-sftp-server.js:394:35)
   at SFTPStream.<anonymous> (/Users/ianbale/Source Code/noderail-data-feed-manager/node_modules/node-sftp-server/node-sftp-server.js:255:31)
   at emitMany (events.js:146:13)
   at SFTPStream.emit (events.js:223:7)
   at SFTPStream._transform (/Users/ianbale/Source Code/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:572:20)
   at SFTPStream.Transform._read (_stream_transform.js:186:10)
   at SFTPStream._read (/Users/ianbale/Source Code/noderail-data-feed-manager/node_modules/ssh2/node_modules/ssh2-streams/lib/sftp.js:170:15)
   at SFTPStream.Transform._write (_stream_transform.js:174:12)
   at doWrite (_stream_writable.js:371:12)
   at writeOrBuffer (_stream_writable.js:357:5)
   at SFTPStream.Writable.write (_stream_writable.js:274:11)
   at Channel.ondata (_stream_readable.js:628:20)
   at emitOne (events.js:115:13)
   at Channel.emit (events.js:210:7)
   at addChunk (_stream_readable.js:252:12)
   at readableAddChunk (_stream_readable.js:239:11)
```

I can't find exactly where this is thrown to try to catch it either. If happens before any of my handler functions are hit.

**Comment by uberbrady** [comment]
I think this is the same as #33 

I assume we're doing something weird/wrong in our call to `open` - and it works fine on a nonexistent file, but doesn't work so well on an existing one.

**Comment by uberbrady** [comment]
I wonder if the bump in the ssh2-streams library might have fixed it? Can you check out the newly-released 0.3.0 and see if it works any better?

**Comment by ianbale** [comment]
It does look the save as [#33](https://github.com/BriteVerify/node-sftp-server/issues/33)

Unfortunately 0.3.0 is not working for me at all.  Using CyberDuck (My usual FTP client) I cannot connect at all. Using command line (from OSX) I can connect and do an 'ls' and receive a directory list, but the server crashes just afterwards. This is the debug output when I try to connect:

SFTP Server: on('authentication')
SFTP Server: on('authentication')
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:44,padLen:20,remainLen:32
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: undefined
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
DEBUG: Parser: IN_PACKET
DEBUG: Parser: Decrypting
DEBUG: Parser: pktLen:60,padLen:18,remainLen:48
DEBUG: Parser: IN_PACKETDATA
DEBUG: Parser: Decrypting
DEBUG: Parser: HMAC size:20
DEBUG: Parser: IN_PACKETDATAVERIFY
DEBUG: Parser: Verifying MAC
DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
DEBUG: Parser: IN_PACKETDATAAFTER, packet: undefined
DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
SFTP Server: on('end')
user disconnected


Cyberduck shows this error message:

Uncompress: inflate returned -3. The connection attempt was rejected. The server may be down, or your network may not be properly configured.

I trued uninstalling sftp-server and ssh2 before reinstalling from scratch - just to be sure. But it made no difference. Rolling back to 0.2.7 got it working again.

**Comment by uberbrady** [comment]
Excellent; let's work on the Cyberduck problem in a separate issue, once you have something for me.

**Comment by ianbale** [comment]
I'm not sure what I can contribute as far as using Cyberduck is concerned other than to say it worked fine with v 0.2.7

**Comment by ianbale** [comment]
Looks like the Cyberduck issue is caused by an SSH2 issue:
https://github.com/mscdex/ssh2/issues/607

**Comment by uberbrady** [comment]
Hrm. Well, it looks like compression can be disabled and thus we can work around the problem, right? If you get a chance to play with that, let me know. Barring that, I'll take a swing at it and see if I can push out another point release. Once they fix the problem(s) in the ssh2 lib, we can update the versions we're requiring and perhaps put up another point release.

**Comment by ianbale** [comment]
I can't get 0.3.0 to work for my use. I have a supplier that sends us data and I have no control over their systems. They've been helpful in debugging the issue, but now that we have something working, I'm unlikely to get a lot more help out of them. Although turning off compression works for Cyberduck with 0.3.0, that does not seem like a great solution - but maybe it is their problem rather than ssh2's? 

I've ended up using a modified version of 0.2.7. I need the 'password' in the reject:

  ContextWrapper.prototype.reject = function() {
    return this.ctx.reject(['password']);
  };

otherwise they simply cannot login. I tried putting ['password'] in the server.on("connect" handler, but that does not resolve the issue.

I also resolved the overwrite issue with this nasty hack. I was seeing a value of 18 in flags (and empty string for flagsString) which results in the unknown flags error which kills the server. By watching for 18 and forcing it to "w" resolves that issue and allows files to be overwritten without issue.

  SFTPSession.prototype.OPEN = function(reqid, pathname, flags, attrs) {
    var handle, rs, started, stringflags, ts;

    if (flags == 18)
    {
      stringflags = 'w' // Fix for cyberduck overwrite file
    }
    else
    {
      stringflags = SFTP.flagsToString(flags);
    }
 

I don'y know if any of that is any use to you? I'd love to spend more time looking at this, but I have some quite ridiculous deadlines ahead of me, so need to focus on the application as a whole any not worry too much about a more elegant solution for this.

**Comment by msjoshi** [comment]
I'm trying to followup on this conversation and have a similar issue. How can I disable compression in v 3.0.0?
