### ISSUE TITLE
Error: invalid stored block lengths at Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by adonisv79** [BriteVerify/node-sftp-server#41]
I think this is an issue with SSH2 as well. anyway here are the details

Environment: Windows 10, Node 6.10.3

sample host.key file
```
PuTTY-User-Key-File-2: ssh-rsa
Encryption: none
Comment: rsa-key-20170911
Public-Lines: 6
AAAAB3NzaC1yc2EAAAABJQAAAQEA1ICg6QtXTCQ89bJoWe3lHnLHuMyWNO4G9DdQ
ICPH47nqVlugMWnj+ytArbo/xL46MpABgTs80v8bJApTU9Pu/nnn++CHoYHG6M3L
gp1u/tGOCHtPSylglrZzD37Tfwlc1jfRG0N00UeLtE05kXvmxD4ohl7IBcsqKCBk
t0DaPe2Yp4Jw/QayLm9UIX8pCutuf0lz7zn017D/pRxS3TJLZIKSpJ1IDcMORIrC
YvuL3jTRwawf10ap+ZbwD94ADs6mQgTJww5A7VkyumMDzf00SrApiPu+B/J/3yjW
49Hp4HGVfwtaV79AlxKQe51U9Re4vL/hwgKBmO8U8Cp1gaKSkQ==
Private-Lines: 14
AAABAQCbEcGHdvqDq73IDJFWYX2ub28l/ROqFXqyNjONEzEAH+JasZCSwuSih1i2
ICCyKfMd+mH2hSxinnuW1xo2QLVR6kGAc2nkjyJyiFY8uBK58t1EdaiQyyrO2Cpz
F1wQmCEmsxwM+d+fouln5VOF1vSBXcqLkUXattmS5zS9E6YtL4K2tj07enEPmagV
2z5UQFJtTg22/5yOzz/JNcLLPs1h/hEqbBUgJ3SYwRT9/L3n6MGyaM8Xso+2WjQH
rnsaCf6yh6O2TjmWX1fyfO6OS1EKACRvGoTmu87zG+7QMJ6+wjYfIcLFOvd7S7uj
5b+b2c1AcaGSm7wUE2WEr8up/tV5AAAAgQDtxQ5HolKBAf/+6WB/WZTzbrhPFgDL
39kCgUvuftbI4nsnwtkxxP20zKZaJnuItsUW2UgoRt//cZEUCTrjnVMWBoEMLgwR
B3eGEsPWPSFI/ZD/EfW575tip5ax8mxJjJo+RoSLdy/ILDwD9GQK9Sa0YoqlIR2A
GGlG5BQMkXDxywAAAIEA5MugWi8fXVltW+rCz4m79yVyCJKYgdVTrzYB+p0rX5Ny
XNcKDEwdgMx8/54Ssw+PlQbd0koAMXGwLG3jakRRbBd0h+cIxImX6EhcRXiHq6e2
rK9c7ygAaepr3a4seu+dyq8MsQGwcSCxIxhmvq8b4ZmZhSPWs+nAjsgJD3kD0ZMA
AACAcGMFN08P+LS+XgOYd47z3W4QEDWfyXbme7reogAO3N/PvX954Z7ikhpnmO9g
rdinSK6rm7FICLXwxbiiYuN5p+HPgGWckt9Gni0YiK/RYeM4fsguoJInMS1For2q
qVp6+HlIT6Y93txzqHKf3CTcpKO6qrSmypXC1zIFu1ZJn5U=
Private-MAC: ef3d35e4bdd43bad80dde970934d70ec7c11ee9c
```

sample index.js code 
```
"use strict";
const SFTPServer=require('node-sftp-server');
const myserver = new SFTPServer({
	privateKeyFile: "host.key",
	debug: true,
	temporaryFileDirectory: "/work/lenddo/lenddo-sftp/temp"
});

myserver.listen(8022);

myserver.on('connect', (auth) => {
	console.log('connecting');
	if (auth.method !== 'password' || auth.username !== 'adonis' || auth.password !== '1234' ) {
		return auth.reject();
	}

	auth.accept((session) => {
		console.log('session established');

		session.on('readdir', (path,responder) => {
			console.log("Readdir request for path: " + path);
		});
		session.on('readfile', (path,writestream) => {
			console.log("readfile request for path: " + path);
			'hello world'.pipe(writestream);
		});
		session.on('writefile', (path,readstream) => {
			console.log("writefile request for path: " + path);

		});
	});
});

myserver.on('end', () => {
	console.log('Disconnected');
});

```

runing this and when I try to connect using Filezilla 3.27.1 i get the following
```
Debugger listening on [::]:60142
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: invalid stored block lengths
    at Zlib._handle.onerror (zlib.js:370:17)

Process finished with exit code 1
```

**Comment by uberbrady** [comment]
Are you using the most recently released version, 0.3.0?

**Comment by adonisv79** [comment]
yes

**Comment by uberbrady** [comment]
I put some comments in issue #40 - I'll take a look at seeing if we can disable compression to see if that helps.
