### ISSUE TITLE
Possible EventEmitter leak detected on 'READ' action

### ISSUE THREAD

**Issue by uberbrady** [BriteVerify/node-sftp-server#9]
Probably, one of the things that is doing an `on('blah')` should be doing maybe a `once('blah')` instead.

This is on reading a medium-sized 1MB file, created by doing this: `dd if=/dev/zero of=/tmp/grumple.txt bs=1 count=1048577` and then running the Test server.

```
(node) warning: possible EventEmitter memory leak detected. 11 readable listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Transform.addListener (events.js:239:17)
    at Transform.Readable.on (_stream_readable.js:680:33)
    at Transform.once (events.js:265:8)
    at SFTPSession.READ (/Users/brady/Documents/OriginData/node-sftp-server/node-sftp-server.js:387:42)
    at SFTPStream.<anonymous> (/Users/brady/Documents/OriginData/node-sftp-server/node-sftp-server.js:236:31)
    at emitMany (events.js:108:13)
    at SFTPStream.emit (events.js:182:7)
    at SFTPStream._transform (/Users/brady/Documents/OriginData/node-sftp-server/node_modules/ssh2-streams/lib/sftp.js:599:20)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/brady/Documents/OriginData/node-sftp-server/node_modules/ssh2-streams/lib/sftp.js:173:15)
(node) warning: possible EventEmitter memory leak detected. 11 readable listeners added. Use emitter.setMaxListeners() to increase limit.
```

**Comment by uberbrady** [comment]
Awesome that we managed to get this fixed as well in your PR, @blargity - merged and the problem is now gone!
